# Example script demonstrating execution of the OncoSig Random Forest (OncoSig-RF)
# algorithm (https://pubmed.ncbi.nlm.nih.gov/32929263/), to generate an 
# oncoprotein-specific molecular interaction map (SigMap) for the KRAS protein.

# Load required libraries
if(!require("randomForest", quietly = TRUE)) {
  install.packages("randomForest")
  require(randomForest, quietly = TRUE)
}
if(!require("ROCR", quietly = TRUE)) {
  install.packages("ROCR")
  require(ROCR, quietly = TRUE)
}

# Set the working directory, where the example code and data files are located.
setwd("/usr/local/")

# Source necessary code
source("./R/listToMatrix.R")
source("./R/OncoSigRF.R")

# Set the network file path. In this example script, we are using a reduced-size
# version of a network file generated by processing lung adenocarcinoma (luad) 
# samples, from the Genome Cancer Atlas project (TCGA). The companion Docker
# container includes the full version of the network, as well as a network
# generated from the TCGA colon adenocarcinoma (coad) sample collection. Details
# about how the networks are generated can be found in the OncoSig publication
# cited above (PMID: 32929263).
Network_location <- "./Data_files/luad_network_sample.txt"

# Read in the network file and convert to matrix
Network <- read.delim(Network_location, header = F)
Network$V1 <- as.character(Network$V1)
Network$V2 <- as.character(Network$V2)
Network$V3 <- as.numeric(Network$V3)
Network <- as.matrix(Network)
Network[, 3] <- as.numeric(Network[, 3])
Network_matrix <- listToMatrix(Network)

# Load the gold standard set. Here, we are using canonical KRAS signaling proteins.
# In additional to KRAS, gold standard sets for 9 more oncoproteins are 
# available and can be selected by modifying the file path below, changing KRAS
# to the gene symbol of one of the other 9 proteins. 
Gold_Standard_location <- "./Data_files/10_oncogene_pathways/KRAS/gold_standard.txt"
Gold_Standard <- read.delim(Gold_Standard_location, header = F)
Gold_Standard$V1 <- as.character(Gold_Standard$V1)

# The feature matrix is compiled by combining Network_matrix and Gold_Standard
Network_matrix_df <- as.data.frame(Network_matrix)
Gold_Standard_in_Network_names <- intersect(rownames(Network_matrix_df), Gold_Standard$V1)
Negative_Set_names <- setdiff(rownames(Network_matrix_df), Gold_Standard_in_Network_names)
remove(Network_matrix)

# Run the classifier. For this sample calculation, 10 trees and 10 iterations are 
# sufficient.
Query_output_results <- OncoSigRF(Network_matrix_df, Gold_Standard_in_Network_names, 
      Fraction_Gold_sample = 0.5, ntrees = 10, max_iterations = 10, balance = 1)

# After run, save the results
result_dir <- "../result/"
if (!dir.exists(result_dir)) dir.create(result_dir, recursive = TRUE)
Query_output_results_scores <- as.data.frame(Query_output_results[[1]])
write.csv(Query_output_results_scores, paste0(result_dir, "results.csv"))

# Create ROC curves (or save them to a PDF file, if preferred)
save_to_file = FALSE
if (save_to_file)
  pdf(file = paste0(result_dir, "KRAS_ROC.pdf"))
Query_output_results_scores <- Query_output_results[[1]]
Query_output_results_scores$label <- 0
Query_output_results_scores[Gold_Standard_in_Network_names, 2] <- 1
Query_output_results_scores <- na.omit(Query_output_results_scores)
pred <- prediction(Query_output_results_scores$Score, Query_output_results_scores$label)
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
plot(perf, col = "black", xlim = c(0, 1), lwd = 6)
if (save_to_file)
  dev.off()

# Create ROC curve to FPR < 0.05
if (save_to_file)
  pdf(file = paste0(result_dir, "KRAS_ROC_frp05.pdf"), height = 5, width = 5)
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
plot(perf, col = "black", xlim = c(0, 0.05), lwd = 6)
if (save_to_file)
  dev.off()
